### ISSUE TITLE
사용 언어 관련 질문

### ISSUE THREAD

**Issue by hoony-o-1** [southkorea/southkorea-postal-codes#1]
제가 southkorea 에 추가되었단 사실을 오랜만에 깨닫고 나서..허허 뭐라도 하고 나서 private을 public으로 고쳐야하겠다 하고 보니 postal-code를 개정된 것으로 바꿔보면 의미가 있을 것 같아서요.

저도 공부중이긴 하니 파이썬으로 시도해볼텐데 힘들면 편한 노드로 써서 올려도 될까요? 음.. 질문다운 질문이 아니라서 좀 민망하긴 하지만

**Comment by e9t** [comment]
물론입니다! 마음대로 지지고 볶으세요.
춘식님의 모든 결정을 지지합니다 :)
